### ISSUE TITLE
Log rotation?

### ISSUE THREAD

**Issue by Jivings** [postalsys/emailengine#480]
Got an alert today that disk usage is nearly full on my VPS, looks like the EmailEngine logs have gotten quite big (67gb) over the last few months.

![CleanShot 2024-11-27 at 14 24 30@2x](https://github.com/user-attachments/assets/0eab7e7f-fc52-4905-9c5a-6ecf46a2d14a)

Perhaps needs some log rotation?

**Comment by Jivings** [comment]
Ah this might be my own docker-compose problem

**Comment by Jivings** [comment]
Added this to my `docker-compose.yml` hopefully fixes it!

```
logging:
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "5"
```
